volumes:
  postgres: ~
  livekit: ~
  rabbitmq: ~
services:
  postgres:
    ports:
      - "127.0.0.1:5433:5432"
    image: postgres:alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pguser
  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
  livekit:
    image: livekit/livekit-server:latest
    container_name: livekit-server
    command: --dev --bind 0.0.0.0
    ports:
      - "0.0.0.0:7880:7880"
    volumes:
      - livekit:/data
  app:
    build:
      context: app
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
      - "8888:8888"
    volumes:
      - ./app:/app
      - ./logs/app:/logs
  app-consumer:
    build:
      context: app-consumer
      dockerfile: docker/Dockerfile
    volumes:
      - ./app-consumer:/app
      - ./logs/app-consumer:/logs
#  front-end:
#    build:
#      context: frontend
#      dockerfile: docker/Dockerfile
#    ports:
#      - "5173:5173"
#    volumes:
#      - ./frontend:/app
