version: "3.8"
volumes:
  postgres: ~
services:
  postgres:
    ports:
      - "127.0.0.1:5433:5432"
    image: postgres:alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pguser
  web:
    build:
      context: backend
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
  livekit:
    image: livekit/livekit-server:latest
    container_name: livekit-server
    command: --dev --bind 0.0.0.0
    ports:
      - "0.0.0.0:7880:7880"
    volumes:
      - ./data:/data